name: Git Workflows For CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js v18 from NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm install 18
          nvm use 18
          node -v
          yarn -v

      - name: Install PM2 globally
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 18
          npm install -g pm2

      - name: Clean up lockfiles (optional)
        run: rm -f package-lock.json yarn.lock

      - name: Install Application Dependencies
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 18
          yarn install

      - name: Delete Existing PM2 Process (if exists)
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 18
          pm2 delete node-js || true

      - name: Start application with PM2
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use 18
          pm2 start yarn --interpreter bash --name="node-js" -- serve
