name: Git Workflows For CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deployment:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js from NVM
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use --lts
          node -v
          yarn -v

      - name: Install Application Level Dependencies
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use --lts
          yarn install

      - name: Delete If Exist Process
        run: |
          pm2 delete node-js || true

      - name: Start Application
        run: |
          export NVM_DIR="$HOME/.nvm"
          source "$NVM_DIR/nvm.sh"
          nvm use --lts
          pm2 start yarn --interpreter bash --name="node-js" -- serve
