name: Workflows File For CI/CD


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deployment:
    runs-on: ubuntu-latest


    env:
      VUE_APP_API_URL : ${{ secrets.VUE_APP_API_URL }}
      VUE_APP_STRIPE_PUBLIC_KEY: ${{ secrets.VUE_APP_STRIPE_PUBLIC_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Application Level Dependencies
        run: |
          yarn install
      - name: Build Application
        run: |
          yarn build